### ISSUE TITLE
404 on npm registry

### ISSUE THREAD

**Issue by tbacci** [lemonde/react-native-at-internet#3]
**Description**
I have a 404 error when I want to pull the library from npm or yarn

**Error log / Screenshot**
![image](https://user-images.githubusercontent.com/19467287/111767662-44caf600-88a7-11eb-88be-f9c6849a7af5.png)

**Comment by senorihl** [comment]
This package is not currently available on the NPM registry.
You need to configure & use the [Github registry](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages) or use direct git url in your package.json : 
```json
// package.json
...
"dependencies": {
"@lemonde/react-native-at-internet": "lemonde/react-native-at-internet#master",
}
....
```
And then `npm update @lemonde/react-native-at-internet`
